{% set name = "proxy-tools" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proxy_tools-{{ version }}.tar.gz
    sha256: ccb3751f529c047e2d8a58440d86b205303cf0fe8146f784d1cbcd94f0a28010

  # The license is not shipped with the PyPI source archive  
  - url: https://raw.githubusercontent.com/jtushman/proxy_tools/db43f1e35d4f90a65c5a4d56d9e9af88212ec6e6/LICENSE.txt
    sha256: a428fb8a2e762af3eb0a6edbbb88e9b42ccfee80fd9b423958bcacf9b9abbfe4


build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - proxy_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/jtushman/proxy_tools
  summary: Proxy Implementation
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - traversaro
